gluon/gluon-announced/Makefile
the gluon-announced package installs a hotplug script
that uses announce.lua from the gluon-announce package.
So we need to include gluon-announce as dependency.
Signed-off-by: flokli <florian@darmstadt.freifunk.net>
=> gluon-announced: add dependency to gluon-announce

gluon/gluon-announced/files/etc/hotplug.d/iface/10-gluon-announced
was gluon-announce.devs before
Signed-off-by: flokli <florian@darmstadt.freifunk.net>
=> gluon-announced: rename DEVLIST file to gluon-announced.devs

gluon/gluon-setup-mode/Makefile, gluon/gluon-setup-mode/check_site.lua, gluon/gluon-setup-mode/files/lib/gluon/upgrade/setup-mode/invariant/005-setup-mode
By setting `setup_mode.skip` to `true` in site.conf the device will skip
setup mode on first boot.
fixes https://github.com/freifunk-gluon/gluon/issues/261
=> gluon-setup-mode: allow skipping on first boot

gluon/gluon-luci-node-role/Makefile, gluon/gluon-luci-node-role/check_site.lua, gluon/gluon-luci-node-role/files/usr/lib/lua/luci/controller/admin/noderole.lua, gluon/gluon-luci-node-role/files/usr/lib/lua/luci/model/cbi/admin/noderole.lua, gluon/gluon-node-info/Makefile, gluon/gluon-node-info/check_site.lua, gluon/gluon-node-info/files/etc/config/gluon-node-info, gluon/gluon-node-info/files/lib/gluon/announce/nodeinfo.d/system/role, gluon/gluon-node-info/files/lib/gluon/upgrade/node-info/invariant/001-node-system, gluon/gluon-node-info/files/lib/gluon/upgrade/node-info/invariant/010-node-role
This Pull Request adds the section "system" to /etc/config/gluon-node-info and a new option "role" within "system".
Inside the mesh we want to distinguish normal nodes from other ones like backbone nodes, service nodes (servers like the one for the node map) and gateways.
This will give a facility to react differently on different nodes, especially at node map:
- node detail view
- node counts/statistics
- display backbone links in another way
- see http://map.freifunk-mwu.de/graph.html#mz-uniklinik for graph
- see http://map.freifunk-mwu.de/geomap.html#lat=49.9926050006&lon=8.2622981071472 for geomap
- display separate lists (see http://map.freifunk-mwu.de/list.html)
Maybe other things are possible at the backend while parsing alfred data in future.
A new section in site.conf will be …
=> add section "system" to gluon-node-info with new option "role" and luci package to change role via config mode

gluon/gluon-mesh-vpn-fastd/files/lib/gluon/announce/statistics.d/mesh_vpn
This adds basic peer statistics to statistics.d:
"mesh_vpn": {
"muehlentor": {
"established": 23.8 // seconds
},
"huextertor": null,
"holstentor": null
}
This will be used to implement https://github.com/freifunk-gluon/gluon/issues/98
=> gluon-mesh-vpn-fastd: announce peer status using statistics.d

admin/autoupdater/files/usr/sbin/autoupdater
Hi, I sometimes see a lot of stalling wget processes from my autoupdater on my freifunk node. Specifying -T 120 should make wget terminate after 120 seconds. 
When the busybox in gluon has not been built with the timeout option, wget seems to ignore the -T 120 option.
This patch is expected to work fine, but is not yet tested.
=> Added a 120 second timeout for wget to prevent it from stalling forever.

gluon/gluon-announce/files/lib/gluon/announce/nodeinfo.d/system/site_code
Announcing the site_code inside the mesh would help a lot to distinguish different software builds (different communities sharing one mesh or the same gateways) in backend.
=> gluon-announce: add script to announce site_code

gluon/gluon-ebtables-filter-multicast/files/lib/gluon/ebtables/110-mcast-allow-arp
Fixes https://github.com/freifunk-gluon/gluon/issues/311
=> ebtables-filter-mcast: drop ARPs to/from 0.0.0.0

gluon/gluon-next-node/files/lib/gluon/ebtables/250-next-node, gluon/gluon-next-node/files/lib/gluon/upgrade/400-next-node
Beim Freifunk Hackathon in Arnsberg ist aufgefallen dass die Next Node Webseite teilweise über IPv4 nicht zuverlässig zu erreichen ist.
Ursache dafür ist, dass die ARP Anfragen für die Next Node IP auch aus dem Mesh beantwortet werden und der Client somit eine falsche MAC lernt.
```
next node ip4 = '10.15.244.244'
next node mac = '50:51:52:53:54:55'
358  25.521954 IntelCor_d2:e4:98 -> Broadcast    ARP 42 Who has 10.15.244.244?  Tell 10.15.8.55
359  25.524964 Ubiquiti_0a:2e:f4 -> IntelCor_d2:e4:98 ARP 42 10.15.244.244 is at 68:72:51:0a:2e:f4
360  25.525014 50:51:52:53:54:55 -> IntelCor_d2:e4:98 ARP 42 10.15.244.244 is at 50:51:52:53:54:55
1819 118.212649 Tp-LinkT_f4:d6:f0 -> Broadcast    ARP 42 Who has 10.15.254.250?  Tell 10.15.244.244 (duplicate use of 10.15.244.244 detected!)
5132 …
```
=> fix IPv4 next node issue

gluon/gluon-core/check_site.lua, gluon/gluon-core/files/lib/gluon/upgrade/030-system
In Bremen it has been noted that a prefix may lead people to believe it
has to stay there and thus naming their nodes "ffhb-*", which is not
what the community wants (see FreifunkBremen/gluon-site-ffhb#1).
However, an empty prefix lead to the connecting hyphen still being
inserted. This commit thus only inserts this hyphen if the hostname
prefix is non-empty.
=> Allow empty hostname prefix

gluon/gluon-alfred/files/lib/gluon/cron/alfred, gluon/gluon-announce/files/lib/gluon/announce/neighbours.d/node_id, gluon/gluon-mesh-batman-adv-core/Makefile, gluon/gluon-mesh-batman-adv-core/files/lib/gluon/announce/neighbours.d/batadv, gluon/gluon-mesh-batman-adv-core/files/lib/gluon/announce/neighbours.d/wifi
This adds a new announce.d datum "neighbours" (alfred 160) containing
information about mesh neighbours. It's intended to be an replacement
for batadv-vis.
In addition to the data already provided by batadv-vis it'll also
provide information about direct wifi neighbours.
Unlike batadv-vis, no data about clients is transmitted.
Sample data:
{
"wifi": {
"90:f6:52:82:06:02": {
"neighbours": {
"f8:d1:11:2c:a7:d2": {
"noise": -95,
"inactive": 0,
"signal": 0
},
"96:f6:52:ff:cd:6f": {
"noise": -95,
"inactive": 0,
"signal": -37
}
}
}
},
"batadv": {
"90:f6:52:82:06:02": {
"neighbours": {
"96:f6:52:ff:cd:6f": {
"lastseen": 2.8500000000000001,
"tq": 177
}
}
},
"90:f6:52:82:06:03": {
"neighbours": {
"f8:d1:11:2c:a7:d3": {
"lastseen": 2.3500000000000001,
"tq": 206
}
}
}
},
"node_id": "90f652820602"
}
=> announce neighbours using alfred/gluon-announce

gluon/gluon-config-mode-mesh-vpn/files/lib/gluon/config-mode/reboot/0100-mesh-vpn.lua
Fix: Removes the trailing newline from the return string of the "fastd show_key ..." command.
=> gluon-config-mode-mesh-vpn: Remove trailing newline from pubkey variable in 0100-mesh-vpn.lua

admin/autoupdater/files/usr/lib/autoupdater/abort.d/README, admin/autoupdater/files/usr/lib/autoupdater/download.d/95drop_caches, admin/autoupdater/files/usr/lib/autoupdater/download.d/README, admin/autoupdater/files/usr/lib/lua/autoupdater/util.lua, admin/autoupdater/files/usr/sbin/autoupdater
The main change is the addition of the download.d directory, which allows to stop services after the manifest has been verified, but before the image is downloaded.
Suggested list of services to stop (RFC):
* uhttpd
* alfred
* respondd
* batman-adv-visdata
* haveged
=> Autoupdater improvements

net/respondd/README.md
See [rich diff](https://github.com/freifunk-gluon/packages/compare/master...Philzen:patch-1?name=patch-1&short_path=ea39d6a#diff-ea39d6a3dd50562eaa0ac425cb130c22)...
Anything formatted like a tag obviously won't be displayed in the Markdown render, thus escaping the two \<include> hints ;)
=> Reveal unintentionally hidden text

net/batman-adv-legacy/files/lib/netifd/proto/batadv.sh
this should fix https://github.com/freifunk-gluon/gluon/issues/820
=> batman-adv-legacy: ignore error when writing to mesh_iface

admin/autoupdater/files/usr/lib/lua/autoupdater/util.lua, admin/autoupdater/files/usr/sbin/autoupdater
Add workarounds for freifunk-gluon/gluon#582, so we don't delay the Gluon 2016.2 release further by the new autoupdater implementation I'm working on.
=> Autoupdater locking and timeouts

libs/libplatforminfo/Makefile, libs/libplatforminfo/src/targets/template/x86.c, libs/libplatforminfo/src/targets/x86-geode.c
We use some geode based boards as offloaders or for wireless controller based environments. The normal x86 images did not boot on these boards.
=> x86: add geode platform

libs/libplatforminfo/Makefile, libs/libplatforminfo/src/targets/mvebu.c
This PR adds the target mvebu which is needed for the Linksys WRT1200AC.
=> libplatforminfo: add target mvebu

libs/libplatforminfo/Makefile, libs/libplatforminfo/src/targets/ramips-mt7628.c
this enables the inclusion of the vocore2 into gluon
=> libplatforminfo: add target ramips_mt7628

net/l3roamd/Makefile
this adds a basic version of l3roamd being used in the current babel-PR.
Having this allows for builds of firmware with babel.
=> net/l3roamd: add basic package

admin/autoupdater/files/usr/sbin/autoupdater
The list from the commandline isn't shuffled, so if mirrors are determined externally, they can be prioritized.
A possible application is detailed in freifunk-gluon/gluon#454. Also a manual update with a custom mirror, for example on a node that was offline for a long time, is now easily realizable.
=> autoupdater: Add posibility to specify mirrors on commandline

net/respondd-module-airtime/src/Makefile, net/respondd-module-airtime/src/airtime.c, net/respondd-module-airtime/src/airtime.h, net/respondd-module-airtime/src/ifaces.c, net/respondd-module-airtime/src/netlink.c, net/respondd-module-airtime/src/netlink.h, net/respondd-module-airtime/src/respondd.c
* Unify similar code for dumping netlink stuff
* Only add items to the object returned to respondd that are returned from netlink (this fixes #157)
* Add various checks for successful allocations (this also fixes #158)
Tradeoff: The clear line "JSON in respondd.c, netlink in airtime.c" had to be torn down in order to build the JSON directly while parsing the netlink response in airtime.c
=> respondd-module-airtime: Improve error handling

net/mmfd/Makefile
This bumps mmfd to a version without memleaks and including proper command line argument parsing.
=> mmfd: version bump, remove memleaks, add parsing for command line options

net/mmfd/Makefile
this will allow using the latest mmfd optimisations:
* do not send the packet back to the originator
* flush neighbours when re-connecting to babel
* extend usage of libbabelhelper
=> mmfd: bump version

utils/libbabelhelper/Makefile
This will add a helper library to parse data from babel.
This is used by mmfd and the babel respondd module.
=> libbabelhelper: add initial version

net/tunneldigger/Makefile
- Sync package version numbers (0.4.0 = vNext)
- Added cmake related patches to Makefile
The new upstream version contains a lot of bug fixes and the latest commits use the cmake system.
=> tunneldigger: Update to newest upstream commit:

net/batman-adv-legacy/patches/0005-batctl-fix-wrong-header-lines-number-for-local-trans.patch
Backport of:
4aa06a7c "batctl: fix wrong header lines number for local translation table"
Signed-off-by: Linus Lüssing <linus.luessing@c0d3.blue>
=> batman-adv-legacy: batctl: backport TL header lines fix

admin/autoupdater/Makefile, admin/autoupdater/src/uclient.c
Previously supplying an invalid url for download would result in
uclient_new returning NULL and crash the autoupdater as soon as
cl->priv is accessed.
Signed-off-by: Tobias Schramm <tobleminer@gmail.com>
=> autoupdater: Fix nullpointer dereference on invalid URL

admin/autoupdater/src/autoupdater.c, admin/autoupdater/src/settings.h
This commit introduces a new cli flag "--no-versioncheck"
TODO:
=> autoupdater: allow skipping the versioncheck

net/respondd-module-airtime/Makefile, net/respondd-module-airtime/src/airtime.c
The noise value delivered by nl80211 is actually a signed int8. Thus it
must be interpreted as a signed value, too.
Signed-off-by: Tobias Schramm <tobleminer@gmail.com>
=> respondd-module-airtime: Fix reported noise result

utils/uc/Makefile
This adds a smaller alternative for a socat-use case: write a line of text to a unix socket and display the response.
This is used for prefixd, used as debugging tool for l3roamd, can be used as diagnostic for ddhcpd and fastd replacing their respective ctl commands. 
This PR moves a package from the babel software out of the main tree into the packages repository.
=> uc: add new package

libs/libplatforminfo/Config.in, libs/libplatforminfo/Makefile, libs/libplatforminfo/src/CMakeLists.txt, libs/libplatforminfo/src/targets/custom.c
With this target it is possible to define files in the openwrt **.config** which **libplatform** use to look for the information on the system.
I need this to use the **autoupdater** for a different application independently from freifunk if i have another image name convention.
=> libplatforminfo: Add custom target

net/mmfd/Makefile
This bumps the version to an mmfd that will not turn cpu-bound in big networks with many changes on the babeld socket because the babeld socket is not used any more to determine neighbours.
A new mechanism is introduced to discover neighbours via multicast. To use it, all mesh interfaces must be specified.
=> bump mmfd: remove babel dependency

net/simple-tc/src/simple-tc.c
Error messages used `uradvd` and usage still had the `gluon-` prefix.
=> simple-tc: fix confusing program names in error messages

net/respondd-module-airtime/README.md, net/respondd-module-airtime/src/respondd.c
This implements freifunk-gluon/gluon#2204.
The `wireless`-structure provided in statistics looks like this now:
```json
"wireless": [
{
"frequency": 5220,
"active": 30461,
"busy": 2057,
"tx": 4,
"idx": 1
},
{
"frequency": 2412,
"active": 31982,
"busy": 7544,
"tx": 156,
"idx": 0
}
],
```
There's a test router available at http://idx-test.n.ffh.zone .
*or as fallback* http://[2001:678:978:122:b64b:d6ff:fe22:4ebc]/cgi-bin/status
=> respondd-module-airtime: add phy

admin/autoupdater/src/autoupdater.c, admin/autoupdater/src/uclient.c, admin/autoupdater/src/uclient.h
Send the access point's currently installed Gluon version in the HTTP header "X-GLUON-VERSION".
Resolves https://github.com/freifunk-gluon/gluon/issues/2232
=> autoupdater: Add Gluon release to HTTP header

admin/autoupdater/src/autoupdater.c
Let sysupgrade run a --test upgrade to verify that the image is
compatible before attempting an upgrade.
This fixes an issue where a router can get stuck without network
connectivity when a a remote autoupgrade was triggered.
Fixes #193
=> autoupdater: verify the image before upgrading

net/wgpeerselector/Makefile, net/wgpeerselector/README.md, net/wgpeerselector/files/lib/netifd/proto/wgpeerselector.sh, net/wgpeerselector/files/usr/bin/wgpeerselector
wgpeerselector
==============
The wireguard peer selector is a daemon allowing to connect to only one
wireguard peer of a set of N peers. It does that by randomly picking one
peer, trying to connect and upon failure trying to connect to the next peer.
It is comparable to setting the "peer limit" to one in fastd. The daemon
is written in lua and hardwired to OpenWrt mechanisms.
Features:
- Status socket via UBUS.
- Routes for "Allowed IPs" are installed to the kernel.
- Synchronize time via NTP.
- Currently necessary in wireguard to reestablish a connection after
rebooting. [Reference](https://lists.zx2c4.com/pipermail/wireguard/2019-February/003850.html)
- Can change its unix group.
How does it work?
-----------------
The daemon is configured using its netifd proto `wgpeerselector`. The …
=> Add new package wgpeerselector

net/wgpeerselector/files/usr/bin/wgpeerselector
an other datatype in same json structure makes problem an marshalling:
here an object and an boolean.
if there is no null posible, please add an empty object - this suggestes solution here.
or skip the else type
=> wgpeerselector - keep datatype on ubus status

net/tunneldigger/Makefile
please backport to 2021.1.x too. 
see https://github.blog/2021-09-01-improving-git-protocol-security-github/#when-are-these-changes-effective
https://forum.freifunk.net/t/gluon-braucht-menschen-die-tunneldigger-aenderungen-testen/20674
https://github.com/eulenfunk/firmware/blob/0bd533077663c91aac4df232dad685c24763350d/patches/tunneldiggergit.patch
=> git:// links browned out since yesterday

net/sse-multiplex/src/sse-multiplexd.c
sse-multiplexd leaked pipe FDs to its child processes, so newer children
keep the older ones alive when they should have received a SIGPIPE already.
Closes freifunk-gluon/gluon#2468
=> sse-multiplex: fix pipe FD leaks

admin/autoupdater/src/autoupdater.c, admin/autoupdater/src/uclient.c, admin/autoupdater/src/uclient.h
- Patch 1 is cleanup
- Patch 2 fixes a use-after-free (together with https://github.com/freifunk-gluon/gluon/pull/2796)
- Patch 3 improves signal handling, allowing to interrupt the autoupdater using Ctrl-C when it is safe to do so
Closes #261
=> Autoupdater fixes (use-after-free, better signal handling)

net/simple-tc/Makefile
simple-tc hasn't been working since OpenWrt 22.03, as act_police was moved to a separate package.
While we're at it, we can also clean up the other dependencies:
- Remove the obsolete conditional dependencies, these were for GLUON_SPECIALIZE_KERNEL
- cls_basic was moved to kmod-sched-core, so we don't need kmod-sched anymore
Fixes https://github.com/freifunk-gluon/gluon/issues/3017
=> simple-tc: fix kmod dependencies

net/wgpeerselector/files/usr/bin/wgpeerselector
This fixes a minor bug, which happens, if the key has been invalidated by the server and the connection to the gateway is lost due to the gateway closing the wireguard tunnel.
A trace is logged on the node due to the undefined variable coming from a copy-paste mistake from a few lines above.
This is fixed by using the `connected_peer`.
=> wgpeerselector: fix undefined variable peer

admin/autoupdater/src/autoupdater.c, admin/autoupdater/src/uclient.c, admin/autoupdater/src/uclient.h
backport of https://github.com/freifunk-gluon/packages/pull/247
related issues:
https://github.com/freifunk-gluon/packages/issues/193
https://github.com/freifunk-gluon/gluon/issues/2742
https://github.com/freifunk-gluon/gluon/issues/3181
=> autoupdater: Backport X-FIRMWARE-VERSION header and image verification for 2021.1.x
